version: 2
jobs:
  build:
    working_directory: ~/CIIC-2018
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - run: ulimit -s unlimited && pipenv run python3 utils/generateouts.py
      - run: pipenv run python3 utils/runtests.py
      - add_ssh_keys
      - deploy:
          name: Deploy to public branch
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              pipenv run python3 utils/upload.py || exit 1
              #chmod +x utils/publish && ./utils/publish || exit 1
            fi
workflows:
  version: 2
  test-and-publish:
    jobs:
      - build:
          filters:
            branches:
              ignore: public
