version: 2
jobs:
  build:
    working_directory: ~/CIIC-2018
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - run: pipenv run python3 utils/generateouts.py
      - run: pipenv run python3 utils/runtests.py
workflows:
  version: 2
  test-and-publish:
    jobs:
      - build:
          filters:
            branches:
              ignore: public
